### ISSUE TITLE
missing view capability within plugin

### ISSUE THREAD

**Issue by danmarsden** [rabser/moodle-quiz_exportattemptscsv#10]
I see the other core reports have implemented a "view" capability of their own which is linked in the quiz_reports table (created in the record in install.php and defined in the db/access.php file for the plugins.

it looks like the report code in core reverts to the mod/quiz:viewreports capability when one is not defined by the plugin, but it might be nice to implement it's own capability.

Not a blocker for plugins db approval.

**Comment by rabser** [comment]
Added.
