### ISSUE TITLE
wrong namespace in privacy class

### ISSUE THREAD

**Issue by danmarsden** [rabser/moodle-quiz_exportattemptscsv#11]
https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/main/classes/privacy/provider.php#L25

that looks a bit wrong and will probably throw some big errors when someone tries to interact with the privacy apis.

**Comment by rabser** [comment]
thanks, corrected.

**Comment by lucaboesch** [comment]
You can close this, then, @rabser.
