### ISSUE TITLE
Plugin Readme is not explaining the purpose of the plugin

### ISSUE THREAD

**Issue by purnendudash** [rabser/moodle-quiz_exportattemptscsv#2]
Kindly write the purpose and details of the plugin in the readme file. What it does and what the output data, formats etc

https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/main/README.md#moodle-quiz-exportattemptscsv

**Comment by rabser** [comment]
Expanded a little the README, I hope it's now more clear the aim of this plugin.
