### ISSUE TITLE
Repetation of copyrights statement 

### ISSUE THREAD

**Issue by purnendudash** [rabser/moodle-quiz_exportattemptscsv#3]
https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/5b3d1b028a1e356fa47f005aeae00613c3e9b2ff/report.php#L36

Kindly check the same for your reference - https://moodledev.io/general/community/plugincontribution/checklist#copyrights

**Comment by rabser** [comment]
Removed the second one.
