### ISSUE TITLE
hard-coded mdl_ prefix and mysql specific functions used in sql queries

### ISSUE THREAD

**Issue by purnendudash** [rabser/moodle-quiz_exportattemptscsv#4]
https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/5b3d1b028a1e356fa47f005aeae00613c3e9b2ff/report.php#L216

Some of your queries hard-code "mdl_" table prefixes. Kindly fix those using the reference as follows

https://moodledev.io/general/development/policies/codingstyle/sql

and:
https://moodledev.io/docs/apis/core/dml

**Comment by rabser** [comment]
Should be done accordingly.
