### ISSUE TITLE
Kindly fix the coding style, function and indentation

### ISSUE THREAD

**Issue by purnendudash** [rabser/moodle-quiz_exportattemptscsv#5]
https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/5b3d1b028a1e356fa47f005aeae00613c3e9b2ff/export_options.php#L42

Kindly fix the coding style, function and indentation overall from here - https://moodledev.io/general/development/policies/codingstyle

**Comment by rabser** [comment]
Done. All the files were cheched against https://moodle.org/plugins/local_moodlecheck  until 0 errors/warnings.

**Comment by rabser** [comment]
Now with the automated checks, all it's fine.
