### ISSUE TITLE
mysql specific sql

### ISSUE THREAD

**Issue by danmarsden** [rabser/moodle-quiz_exportattemptscsv#9]
https://github.com/rabser/moodle-quiz_exportattemptscsv/blob/main/report.php#L162C29-L163

That stuff won't work in postgres... can you please test your plugin on a postgres db? - note that support for mysql and postgres is a requirement for approval in the moodle.org plugins db.

**Comment by rabser** [comment]
I should have inserted the right code for postgres, but I have to check it.

**Comment by rabser** [comment]
I checked it against an postgres db and it works.

**Comment by danmarsden** [comment]
Just tested the latest version on postgres and Moodle 4.4dev, and when I select one user to export I get the following error:

Debug info: ERROR: syntax error at or near "."
LINE 2: ... ROW_NUMBER () OVER (ORDER BY quiza.userid), user.username,
^
SELECT
ROW_NUMBER () OVER (ORDER BY quiza.userid), user.username,
user.firstname,
user.lastname, quiza.quiz,
quiza.id AS quizattemptid,
quiza.attempt,
quiza.sumgrades,
qa.slot,
qa.questionid,
qa.variant,
qa.maxmark,
qa.minfraction,
qa.flagged,
qas.sequencenumber,
qas.state,
qas.fraction,
qas.timecreated,qas.userid, qasd.name FROM mdl_quiz_attempts quiza
JOIN mdl_question_usages qu ON qu.id = quiza.uniqueid
JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
JOIN mdl_user user ON user.id = quiza.userid
LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
WHERE quiza.id = $1
ORDER BY quiza.userid, quiza.attempt, qa.slot, qas.sequencenumber, qasd.name
[array (
0 => 1,
)]
Error code: dmlreadexception

**Comment by rabser** [comment]
Actually i'm unable to reproduce this error: which release of postgres are you using ?

**Comment by rabser** [comment]
Ok, got it. "user" it's a reserved word and my tests was not enough to discover it. fixed now.

**Comment by lucaboesch** [comment]
You can close this, then, @rabser.
